server:
  servlet:
    context-path: /tvc-services
    encoding:
      force-response: true
      charset: utf-8


spring:
  #staging
  config:
    activate:
      on-profile: staging
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DB2Dialect
  hibernate:
    ddl-auto: none
  datasource:
    jndi-name:

  #swagger
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
springdoc:
  swagger-ui:
  path: /docs
  show-actuator: true
  display-request-duration: true
  filter: true

# loggin config file by profile
log4j:
  configuration:
    path: log4j-staging.properties

#Ficheiro de configuracao da SC
sc:
  config:
    file: "/home/www/config/sc_config.properties"

#customom properties ex local url
app:
  baseUrl: /tvc-manager
  server:
    type: 10
  auth:
    token-name: accessToken

secundary:
  dbs:
    jndi: jdbc/usrlogon,jdbc/dbtoynet

